### PR TITLE
Small typo

### PR DESCRIPTION
**Pull request by maelle**
Thanks for the conference overview!

### CODE REVIEW

**Comment by maelle** [comment]
The change is "try this one" -> "try this on".

**Comment by maelle** [comment]
@emmavestesson Feel free to close this, but pinging you in case you didn't see the PR (I think you don't watch the repo) :-)

**Comment by emmavestesson** [comment]
Thank you! I was not watching this repo (I still struggle with github at times) but I was very excited to have a pull request.

**Comment by maelle** [comment]
😀

**Pull request merged**
